apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rmusic-sigilos-st-tls
  namespace: homelab
spec:
  secretName: rmusic-sigilos-st-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - rmusic.sigilos.st
