apiVersion: v1
kind: Pod
metadata:
  name: switch-build
  namespace: homelab
spec:
  containers:
    - name: build
      image: ubuntu:18.04
      command: ["sleep", "infinity"]
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
      resources:
        requests:
          cpu: "4"
          memory: "8Gi"
        limits:
          cpu: "8"
          memory: "16Gi"
      volumeMounts:
        - name: build-storage
          mountPath: /work
  volumes:
    - name: build-storage
      persistentVolumeClaim:
        claimName: switch-build-pvc
  restartPolicy: Never
