apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-sigilos-st-tls
  namespace: monitoring
spec:
  secretName: grafana-sigilos-st-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - grafana.sigilos.st
