---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAUKez/zXHbx6/Xn632DicNwo3RqGZNEfNFjrAXrGM8bO8uTEgbIskG+O6/bsfAiRd9FrTyLdVs1Ng9H502TTyBwQ7kf9ld385b3LTnvShnriLGGrawgRg15kXJdu//bN5ysK+FzMNRKfzhqbTw3vQzwdAvdU3wF7drxqK5WREU+H4VGInF3vtpzTOxrbPTiQ2oIYrFQgnIVD+nlR2mq2Y7CqnufqSYp5dKZ3sfDY/9HEhVjLyRDV4HBSphEtMGQam1+s6mkkoTntSvROo++8wWePZsDOGVVEwdEh+dghEiCBnir5V3lKejoaWZCus8ilJHqylonDV4f7t+7+3Hq09xhl5SAl8KTG/HO/s1FNm5GWm7Tpk19a8WSg2NPAFkDBUkVLQUexFy82ZIRtfGtLghkhJd/s4IAO0tGD5t0NBwd8aBUTyn/OccVTZYsvkxJV7uNAHCbrxIbNQVIB/QJLR4+Pokld4jSlViJ62AAxwNGSQHdqUrc7qaXndFZlPxAAkgcsZHHDB/Hodi0FyXv3v0WfagUehdsc0ynIX8KbVyGhe4sGu8V2/Edr/yxqes50hj7HHqgejoxlaogW7rSB1cdtuLemTNP7DBnGkNZ05eO6Wd0ICuwA4B9knrkL8X1FnudWBVWvQ8e6HoJkaaX7fsAx53thlm9qx0PGLDGxx6fePYKnhpiDsK+AzssFI62u/YAX4uDLyyP1HCqtF9SwJrdIC9+Oj+piN4es7099RKBWstJl5QlZ/d
    admin-user: AgArA4o0rMh6LKRHU1BWNbhVoVNOzdRCm9XC9Li0H5pajdzksRlVErpFusi1HJhg6Gj4+0AOmzd4HrRCxbxOPH/xIO+Z+GdF5wQRoQ8NFpzGZpnb4NcVHRHdaiG7IRfKYzBpZnz9AabAxmRQPUrTt/VWGRjjq8Qrp4VzNWjwTzSZYMs+Acq+0bJH7osiWTu//b93xKEmJXBZdMBC+bw72u78+KCxQLm78E+Bkv8l2Lt145WKvUjYQgn4Wc0D1wn/M9vOiWb651eR5fX3IdFuY5g9435ErqgGr1wl3ys84PuuyGo0+J0bpT4bW1TXt7eqfbBU681TPeUj1mRbxNkLuX5/g3oVlkNEfxnHaS6qbLl9Io/C5I//T8Cj8k1ajwhYxbxT444kEkTk31h7FhGHIXOEZHXdBxsBjT94Ny78pCOR95oq/Sw0/CDuXbTLuczctW01Ott64xJrxgYWoODbpAWjLizjtUsqXAOOno8TuNaIbdEfPO1EC9QYy+wPCOQ2LTcDAcivczlumNPh5FhCDZ5D2wrOjG8edKuxlOTRNGod0pUlpGSk+Gm8TKnzhcZWdgsXw0oU+eVFlAJL4bKNJCYLZXYfroIKdtzDpBjR9Yf5uUzaqrnYpEqxZn+OGgHkK+ikarMq+n6VmFcwujl56Iok9QHA0TBKN+LOtzRiLNvrM0zqcheqZhYLPHtToKVLJ5G20Dh7Ag==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
