grafana:
  adminPassword: "OOqgwQJOP3EoCZIOKCCgbsDJEMF9VPWJU5WhUwZc"
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          resources:
            requests:
              storage: 10Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          resources:
            requests:
              storage: 2Gi
