---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slskd-config-secret
  namespace: homelab
spec:
  encryptedData:
    slskd.yml: AgAhauxBRFAqJKvQ1SdsgoqRECe/ON7G3nlQDNsDBE41F9Lxq+wRl1ZxXBCGl31bG2h8pjFOepp1pmPuoXoT8W8WUUEUqfzWGyaOQ+0zkvyfLHR6uvUd+eCZMxtBtOzwIbBoDcrbHETEWlIS9pDBi5fXwJFXEqFpz2FhFf/dIMmXNg1XzfRUPjpWkxtv7nm7xxP/R0EMgTU0jG3CaUnB1U6OsISgNwwI/GqYc360Lb/9N7ofuy7MxJqmGj/jPPBbdzTgo3O9J8xq6cFSDmbY4NiFL0n+ytVbe1t/N0ridBZdY1wV9fJq+u8Oa0gUxW0Ek+KXT0JmwyhQeRz3jzizbdl1gcmaHLxzIqYngawTNDAl2kBVaRa0+1vHh+LZOGFt3KoRntYeWLJ5onJdShcAQXafXvWsATjJMZg46h2yXesDDKyNXkzjyscwonvrm1M0D69HLS9l+VUUm09WmFJ+WmZ6L4y7DUC0jXZkODGJUgLnKdkUSCZXxJhsJSi/A9j95RjurOAPQvxjMDda3xQtEvFjhNVGEOqHudE1Pu7Dssv0t0uHt6qSN5z5b5o8TSuAt38rrTE+k63L33b8OQo2QtlVK+JCZbrmZdYcPiNxv4NzfURagG/L8tzmnPTTLr45ukkfZn2Hdv07JKs1DRaXziGRxXMo7m1+3SKusAAjgdlOmTFERVQN9dX8dZcZRzAQOzDblrpBrMreT0LzI3FExKsHn3g+N3TKQ5IVikkacgkZhUEcU6uocm1zJ9HKDXn9MmPqjY60b8AxA1p2ikWqQNjayXX9QzGj4XhBgB7DcR1sDVLMouLOk7PoFr0Zfjeg3qrH63ILFlg9r0NTkr1iRypOSF5lsjvE2+jn2hT1kFKGtV06HK+kuutHkg3SkI1ksgB/auh9z9jWwm2hxUybOjxJKAEChgzglm4IdFcYG3b2hWUuEZFmw4DY6SAs9N98AuYZGl4Kf2HYHwRyke4ONAUUpC2IbyIR7WwH75/GXdGu4vECW7h1LHyY+t84FzrmEaRDi7n4wEUnDacY8laUeYTypncZYdpAMYOLN/5hie6fxVYSrS8dlQhgTBuMDyHIeIFGDfV5rXbfK5gFD7k07ddCP1GEQR95YmQkceejcrcErWEYS9ImVB+m7y6pIoEbZ6WfQ0wId2fS8tXw03X74A2nTbs2QAXm8K3UuwJPZQ==
  template:
    metadata:
      creationTimestamp: null
      name: slskd-config-secret
      namespace: homelab
