apiVersion: v1
kind: ConfigMap
metadata:
  name: slskd-config
  namespace: homelab
data:
  slskd.yml: |
    soulseek:
      username: nuwuvv
    shares:
      directories:
        - /music
    web:
      authentication:
        disabled: false
        username: Nuuvv
    downloads:
      directory: /downloads
      flat: true
