apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-data
  namespace: homelab
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
