apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual 
  resources:
    requests:
      storage: 1Gi
