 server:      
        interface: 127.0.0.1
        interface: ::1
        interface: 10.0.0.1

        access-control: 0.0.0.0/0 refuse
        access-control: 127.0.0.0/8 allow
        access-control: ::0/0 refuse
        access-control: ::1 allow
        access-control: 10.0.0.0/24 allow
        access-control: 10.10.0.0/24 allow

        hide-identity: yes
        hide-version: yes

        auto-trust-anchor-file: "/var/unbound/db/root.key"
        val-log-level: 2
        aggressive-nsec: yes
        edns-buffer-size: 1232

        # Local DNS overrides
        local-data: "music.sigilos.st A 10.0.0.210"
        local-data: "torrent.sigilos.st A 10.0.0.210"
        local-data: "prowlarr.sigilos.st A 10.0.0.210"
        local-data: "lidarr.sigilos.st A 10.0.0.210"
        local-data: "soulseek.sigilos.st A 10.0.0.210"
        local-data: "tv.sigilos.st A 10.0.0.210"
        local-data: "radarr.sigilos.st A 10.0.0.210"
        local-data: "sonarr.sigilos.st A 10.0.0.210"
        local-data: "bazarr.sigilos.st A 10.0.0.210"
        local-data: "requests.sigilos.st A 10.0.0.210"
        local-data: "pic.sigilos.st A 10.0.0.210"
        local-data: "sync.sigilos.st A 10.0.0.210"
        local-data: "docs.sigilos.st A 10.0.0.210"
        local-data: "cloud.sigilos.st A 10.0.0.210"
        local-data: "backup.sigilos.st A 10.0.0.210"
        local-data: "rmusic.sigilos.st A 10.0.0.210"
        local-data: "ntfy.sigilos.st A 10.0.0.210"
        local-data: "proxmox.sigilos.st A 10.0.0.60"
        local-data: "grafana.sigilos.st A 10.0.0.210"
        local-data: "argocd.sigilos.st A 10.0.0.210"
        local-data: "adguard.sigilos.st A 10.0.0.210"

remote-control:
        control-enable: yes
        control-interface: /var/run/unbound.sock

forward-zone:
        name: "."
        forward-first: yes
        forward-addr: 10.0.0.220
