apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sync-sigilos-st-tls
  namespace: homelab
spec:
  secretName: sync-sigilos-st-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - sync.sigilos.st
