apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
      - name: jellyseerr
        image: fallenbagel/jellyseerr:latest
        ports:
        - containerPort: 5055
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        hostPath:
          path: /var/lib/k8s/jellyseerr
