apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        env:
        - name: LOG_LEVEL
          value: info
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        ports:
        - containerPort: 8191
