---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garage-secrets
  namespace: homelab
spec:
  encryptedData:
    GARAGE_ADMIN_TOKEN: AgB+WkVabA51nkDEOVqKZU8LO1X5ExU4xIXNXV/pWz94db//X8gxy1o5NWZmCYEPYZSHcYKyUmrv9F5x1ljyEXYohLbVu6qWStjNJQJunhj8w+IOF7TT1ryC4Z9czgOGHFZa2FaXOGPZspUKqG3WG1Fi5e73KrrJLgibUYaYRjvSnivPOtsfWdvE+6X4pjInedyD3rVmB1Jci6kDxmj6Exbh8mBfqpWZ7K+RHlDZG+zSaLlLXfIbXXMp0pahP2l/SHd17Y+RpHJe0wEPkIkx15YDl2na/FqmbL+t6zPtXcCScwoCpoES4o+7uim/5N4UIJAGP3PT7+ssNZQi572ho0MOycio5EF3pnZj/2PqVyLEe1FCLn78Ycn7zNGfOJSJ3zx/3Q/Y6+lZZApNhXf/KvTLheVmYKle6mbZvv18nm0xPt6sion8vwB2l0i8EX5zeYRjl1Yg6i0F80TrTeczAPr1R7sCpoPDGW7EApA2Xngfvp2R7SIFe56gFvKTeNGt2JOC7BE+FVQRSTdwsP3bwlQvhS3ffZHcoIkWJEOyv7zrD29GiJZ3YB56LtLzI57TWQuH7ufX0+apzD0sdaDmSwjHO3W1M6SGPhK1MtCkIxVoShUv68rPCm/RrGujISgDsL+8XizuIdIJgpD2G50a6AhqrWO7EByN3UXO6aOFNBr7L8WG/sX2MoADeVlfJYv7IeQIC+7MZz1SkGWLJ6XTwWXfpCMJI43QSYMIVu1v8xkWwAKR7LEnqd7kVr+AEWisQYqt7hepbp7zcEY4VV8MEbd4
    GARAGE_RPC_SECRET: AgBWTqulya351gSomNN5nbvf+W67uJIr0U5WqOvAFaYtmP+fLpvLKF0hLd1+4atKa0VM1iOyu3nStgh4SjQ6WLqIiNji53rLhZUFtesTpnLGx+N4wf/5hm7g19326KiRNNkoy4GpicAtkBsPShhUYM1/1xacgJPSv1khbl21BUnk8Fa4x3fuQvDBAeo/yZylm6/9rZQVrg3joNWUjw5m8DiBaHBBLj/pKN+ObOPRwCtMNJFU/IJY+FqvvqZGE+4UbtMVbgw2E5klYQ+Il4+5ozUXehhMNYZl/QONIicduKrOn8sbtUgPyzNDcsHkuk5KdyvClfi16lTdl4BBesZBGaxO22XY5NbQuFIdhFyaUWyQoD7frW2B/av0Ay1wGX/lShX7okJnAmXOfeq1NQbcsN4++ZA5f05y7SB/i4Aifp7B1RH90E6sZBYM4VPX5SMJ03Y2zGwB2zn9Zfq+oN7MZTlCylNcg3SobOSwK7qpflKawRpaDVjfkLjrXXxi9ZEMELcUJAKfsyN8pKr5dJXn3DlBv6XerWk0QUGT4qaHJIe66divU/Li7rCz/t9uIx2I/9yoQjDUkD4b5jNNycXRLlsAwo1yxuRIIm1rUx/RBjnOH8+tkArz1R02E3Clf3hoBw8ebIdJqXrG9X+oS4Oe9QfYEu5l6lXzckWHC5LBqpsHN1u3RD8V9iwOrmp5B//RNI+xR6EEWKYki1L0U4kPZQ1kOwxQNsNV2pTWEzEtR4/GoWd4Fphq23n5MPYrrmUpm5HoCDrII65j8flKssd1Zra3
  template:
    metadata:
      creationTimestamp: null
      name: garage-secrets
      namespace: homelab
