---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-credentials
  namespace: homelab
spec:
  encryptedData:
    admin-password: AgDGxkZZ0ChlqavpnvtBJQ1nMF9ZVqAYhwG8dSX5vfZT7O0FbkuT0wGW5xVHn+zHUjFAqrFTiKegDKiQiwFoIdh5P7lD6YBzETiESPGDwRJTu1kzHg7MhGl6GJN3EEUkZm2yTE3SIqk9HxawHL7/f1x5fjCW7QZXDlm+rScLlI2jT90vhk/ztEwqQVJIJz0+rGnyUWuBBgxk8J5I+SQ+3X2e96fL7pU4aR8rORXKQoWqbexehski3NDxKJGPPAho9IjOt2Bq5kw7l/W/rteKnYDwNzFDNDrzdd/w7VmBxaIzqlMC3hFX9dYVdU2Aw6XQ9pAuK6LD0JgZBuX0+EifZpVS4K9y1cPDQr4H2FeI6RmUohNxUbkjapSkuLsrs7X5R2OY7PEdjpeAWHrSajnZcXjajDtATum3F6cYQ8cHMIJ7Z0mCfPipOAEHtJ8fbmf3K50fcIyGXHbN7TxjxEaFVzyzdvEI1waNjq5zgypg9Xhq/CkI2t3HCunUtmmgbUBQdMf+/45FbBTBTurpSxDds4+PVu0G0c8YVaZoajH42ROllcsVQmtJvnHUEbFBLA4Rex2xIKGkRJ7rjVZHPrKA/yfxaMeS83qHVJSCZs04KJgeUHRz6ylYV4lfAFsrWgT2cEnGeYIg6ihzUdgQFmqLPzzhF//gOb9xa9GgR/SSmc8a/NEHaWTZU85hfiQriXuQbj4I6sIYqVOfzQef7qDher3NT8D05PAb31HLuLF6CeIQawmeVQFO3EMK
    db-password: AgBS3T6vIuoDjXoYlyCl4UGN9vSYBaFCfKgVQPnJCfWdkmVhOS8St9n4E6di+qTlJJi6/xKVOUgAKfEvJupWzvzU0iUR4LeDhP23QsUqsHV/qMJLL3jCvhQaw/QSfMV+YmdIjyufBpKJYFGotSpwFYJOkeQouEytA9wVHH9r0Y7dxoKbbHFOA/k/bKUqXi8qmQopRG+Ye+87vRF9hGNELr5BAl7z2YpLgjUwjEZHsnzULL+4vM0zGqKej7WcCKD1cQiihwSuyDQQ9Ab8Pq5KJ74GxsJ0PJMMye2STwD48ypogKCNedRTv3UINvyRV8wJgzsm5m2yedIknNS38U/tX2BJuUkMHOnFjoBKR49bAkXstAYLYGvhPbsop1HBnwJB1rAO29FH3wXrZ4QxM5RusHoKaw32vKYBqmbzC0rV2/ksW77gBKng7u5TDooiVYgan46NSa0RdwFKnDIsxrFLxlYPDPgqR/Y6VOnVWyW+/Oe76PF2eVIS2o6bDNKHdGDWA8zmeO5movdeY9OR2NtvrmmxBW8JpLKNQi8JoY4TGRXZKj9oj/kc7NftQxxXASX1aTEiFKFCOEi5N+sx0GJw/dzSPKhhuMeB6kFOnS/IksA1L4T6Kom2MNUc8xD2Z3pEOsM3LyXUf1uLQ3Bjdh8owNgrwI4Uxlg1FjbDH4zR5KLr/82eSd/Jfe6wTlg6KGKdWgL/C9/GS3zOlPBrWxzkn2hyd0+HiJJp/jRHu7qpsLY=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-credentials
      namespace: homelab
