apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  default: true
  provider: aws
  objectStorage:
    bucket: velero
  config:
    region: garage
    s3ForcePathStyle: "true"
    s3Url: http://garage.homelab.svc.cluster.local:3900
  credential:
    name: garage-credentials
    key: cloud
