---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAjlVew/o8gg78N7PIiqFV8JifbrRsvNVoQFdVhpKQmIV7lDeHKgN/MOoHzwJSkE/diPVOk8qBSY5roPwdsNQxgK86WfvBdTINs+Jn1W8nVNxd2LIZsyUCnfbDVxTa2635wQrdkfE2YXbWlQuPzJ5yIuVKLqdp1RHOmiHqfcC9pH69lsWZtLHA1U1zfrogoChH2tJ5Ypkgdz4EGbQPC2PGxdkjKP2SDczbv9OHUB1Zn4/aQF0oFDgXDrojRxy05dlpVwjSIUfWmnI0MkE3m1R+7IZftgtOIkZ5kWaJvgj7H2815ldNHJ518TfbBQM/bypW0PqtdP/QuWU5fMouoNNXRYr0gJBxnfaGLRt/UQh5AhhaMuyQ+MXBCGddxUoDmFrN9I9AJmXazuOB1Fd/lJWbDMjkWDUYT3YLiwFglwG0ar6QD9IGagnU3noQnMxHyjUQSvYNbhTlA784kn6eEnTwjqhZ6DEr0wT3ScxiEXCBoaAwjel5+fYeAnJ35ERy3NBhm9axiIXkN1wV7o1ukScXFkk5pIpCN0lXUZr0MjB96jKL5wQ88OOgK77CDRqNKa0EdmgFDAlM3Y4zwveqpdoIGoo34z9qdvYNPfXIgbRj7RW8nelTeKP0AElW6LZ4y9figm1t4mUiWbqQMEyxhckOBkVQu4Hrh8+/7NIRTvIiFRRPbSARGxNogMOVDbVbV6wrKGVbTNDuapLTLiaDBra7gQwsg5VJwJT746AN0R3lDyoUhQJaYw5aQbHY3LQPsNOWistPS161MfjynF1NvTh+UfBl5Yo32s0laYPxI4NIRX3L7bnpnm80vwAzW8fEeZ+3A1sgDEw==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
