---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garage-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBmPM5tcIcNgVksxurvZeaEvIMIeQ7VRBDaoIHpKkW01iLNsi46HqfGFsGxAB+FC0krDw4TuiswFjClugCbQa2SywUHHSjLF7FRVdt3AuPIYnyWX5WuBpdBcdIAfRAIYgNrm3UNrMfHnK7Dl4+wcccnrox3gwHlR0ry0Rv9DdRArAvj/clwqtUXeDq8yblw5rSZw1v4BBZmRstSzVp9k7CxitSCXM0+5rfi/Iki0BTrHjQ13wYMHJ3+Eb/d5L7a1CD7nicu64kH4vYKB4LjXWLTrXM0WBvLDjL/+8PdCLKqgLmO9cD/Dznesqnc6q1g3pa2t2TKn0aVrbjNrDcunRGpQKHGlY+Q+lJynVgcPqwkOevs8lTZVfPtybvelvDQjBxLYo/v+jBxniY+ZMorOt30cHVABB1Z55WfxHPXjCbndNIY5Vax6JOHaTloIztNmMjjarmFi+MzQDahUdDtnwU7fLcwnjpPhV46KYuJ7yXQeF3pLhcX+XJajhU/R0ppaT8TdT4pW5Oh7PjTcZUdsh/xi7p02z7JWn6M3kXRY6oQmd4MbeOZ0BGIXzxDiiaAPxe0i2/VOG57l+nohPHkzLtzTN8N+CrdVxK907D90hS2r58zcMK4SGJVOcgWocszTweIv2dP0QBpehzsbNuDalzmSWzvj8DuB0w0PEziynhJ7j9MQ7aGx8H2Rxil2IIOSYvjBaj5cq3Fin55HBZOjk2eZY8iZWcN0Zu5TXI/axHkjLhkVlgwEhXLvLCZNAAcRW8e9lJ+VXqSdFsKErmVcrNIY4F+GNSH2HqClyYC1qBhTDYWc/x4mh/QIkRc/CcWuw2YHeNkiJU4QlKWIMnvITYiuiW9C2i4AEJ1tiKEnUSeGBzkXHBndZWms6f6FWmZ
  template:
    metadata:
      creationTimestamp: null
      name: garage-credentials
      namespace: velero
