---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgAM5OqvCY1jhQuukbmR3dr/XOlZNe3rNgsQtgBzmTU6a2eFPh8vtZ5pJs5BfZK5L82L544aXLSRzSLaZzcA+Gm018KuG4+w5MCgCF2BBxser8ewZj1cKLmkrbxjtls1wy5ZKwJWvq/VVyxtfYeGZ34FkSu5+sC2ELe9QquVdI5JdYbNd7GIfpXyzNm3XbCDdaDNttqVxec64gk+swNX9NLfl/5BjEBHCO381A+OhJxnLSXz26lozuDOzKnqdKdNsHxZzPrbUNbhfp/01kByq2QE1PqWsUMh+AIKLIjrrPICelKk63b5YrMNMvNfPW7VpT8cRKCTzyhzfEGGDYRNCQV6V36oOH2osMzimgL/SVkJFovLHaExvVcT0w5xvpIAaykA1soUF+/FYIo7iwfZ/FqqBc2kAQUrsLZ5HIY7CD6Xd9k9or7H1/mlvOZO2uyHjz3T4VP1V/Bg74grA2rLxdXuLwpH9Tgza8k8h/jgbBcMxrwnNjU3YwTtvem+eOiq+xUb/vNzBXI95rvMg1fbgWoPhSSO+ejqKUQLWn3FbojK7E7Hc79/9WT71aWKwvIm0a2+lij4594r9Lkjx8vleU4+ytXa2XaRM0Kf95QkOXOM4Hyg5gu+JE+V9vudgmhGYpp1+SzFAbkJ7Q2PLljqvwufyx6PEijdSOHmD5CDfQiLBDojauR/LifV6g08z2LZi84aYavTPdAac64VbUW9UNA=
  template:
    metadata:
      creationTimestamp: null
      name: velero-repo-credentials
      namespace: velero
