---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCfP2E40W373gSYs4JjyXduGfmFuoJvIf2DV5jWCflqj7ce3TUMEMTZ3OeFdhx3TZZwjgZixKEuimvX35td+qwxO5S09+0+24z20M6IeinHSLnUtyLDMFXwUkR8+t+B4ZiLIWrR7hVA3JvQbpvI3tTN2mtefSNvx1BUmoj5c/sOwfHnMfDhiSVA3gzl6CBkq/v6SWPZAwcHqT/uezM0O4lFJeiiGafQc4tyjm0jnXRqAq3yCSPMPws4VJXGNXo6ukFu4e38an9PC6AQI2Eg7r2sEY33v+xK+eh/zfePhmyilxoysqh07bV11FgHvv0MzVCr9PZ5GiL9JNfwJet+/QT082FUPzxKHd3H/WHna6J+D02QIfJjQW3yNkqm42gdvEH5MtS8W0zNBqb21FEJd63YC7NyUhgkBjF7WCZvCT6CCb0lmbVr1izZSGy2XoLBygRhtRXdwQ4qEcy0vwLxUhZIrd/0pajj6Gd3SSaqB1zzn7TJkpQjMm6zl7cDs3Ti7eYz76/Dwuy315lQuxyp5b2gk1eO6ivp1rxiB5EpKtvFFBzeookerMeTNAXj0jQVRbWQ/vi7rGeK8Ozh9dmIKcLq6J03B4gnPzCZKcdaDseppgSfgGHj5IxvvMs35GAlWnNr+6oOoYPUcZun+7WGjHpKglk68kV359lA5T5lhn08CCX9a6lhqXA670INA+tUViLxbPUHYxaX3SIhZQ/tWK6OpxJdsZZIDmbVa4mwLZTn0ktVKIM4t9C39US9aGbl46+TimhsYlNipCys1QrOQR7HM4pUeB/7bhgSBgIaut6HTDJ0WhprrjvQIdMYSmDyuWuzHspOs/zh4iPOW8aghiA=
  template:
    metadata:
      creationTimestamp: null
      name: velero-s3-credentials
      namespace: velero
