---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-credentials
  namespace: homelab
spec:
  encryptedData:
    db-password: AgA/QmJGjlZ4B334RoTxxdwNGWeC0On2uqPYhcV5/TYw5VXkWBPMDjtEBSSM6XmsL8rv5SxjDYsPasNe6lKENdNKTV47+77UutfKWbLW+yGxbDGKmu9J5usd1jx4qiAwBnoguMrrz8zHw9YGFKbWrW/QIDf1zrT4bp+4P0lbzRtxVZu9D7GnXY3i28cgEa2K1gtWqiSnlc8WJRBdNz+iuAdW78nzmSiwvT7zd6vtXoW2e/qXzZ2dJ54Y1Zt1IYyPBLg5r+S/6JJlh2bIt8yFE6WiTgb0zn/jf2HX7aTZgsPbvvWUpDX5sb5NV6uo/J94XK0a31vqfN8ncsYWvj5psWaomJuK2vBreQsEkzxzinCun2C41MZQJ5oB/Xx+EG5e9HyijL4jfcLhSum79Ii6C2qqBDe+N1m9Uhl3DbSyHX19zRkUZqDF8Bp36N4l+BZ+avOepwdigvGs5i+EneXOMJx7tNJu586DdE81H4bGRYOTKX/NjRLQ5IQ4vbxuqxI2zd+BNPbcBGWv0M19P+bF07KmjhsSWbqZBW+F/uSu7KfeJcsgZY+jQXaqM6pIjtUi+/5r6x6cp27jBEEPfv32QM1Go8KtQDg87/uqHx2nGF4Kjn/2NQEJjN26arun6vVKuD6HSTD3K2b4V4Q0oke6Om9Mwl7MLYgEtKK2QhwFCixPux399Onq364y0BGuZyAWsOF9NyBEVl3HiC9aIIl+RMeI2D4hJyOvLlBaxJPiaaU=
  template:
    metadata:
      creationTimestamp: null
      name: immich-credentials
      namespace: homelab
