apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-sigilos-st-tls
  namespace: homelab
spec:
  secretName: adguard-sigilos-st-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - adguard.sigilos.st
