---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onlyoffice-credentials
  namespace: homelab
spec:
  encryptedData:
    jwt-secret: AgCnp0VxkBlQuQGX/Kz+DHv+uso4eYWgutDiK6whaWxCyQzFuxRWNzzMTbAuyd9Z17gUBiDuaJAOfbxBntLc6oCnATmwF6iVpOo4Xo/X6l/Mi6kjc6kdTAa0jmS6X9TQPQvwQIvxwV26nbV+A4/xjC5rQyDkYvfRLryHRqz8oI1swuWYyV9Ps1oQEOq1fBpw1qp0fIWAwZn1ZL6njwHo6Mstru59NbB6gqppkkr39bDQL/3Qf8Z99Sk3iuaFCdxx42QNthrFzMcFcjDXgotivSzG+H/1qQtLWSe2MqRFyU3qVVLUJ/5Qf00NMRnNdZug1c3zqwbLT0blNSd+25BcS94P3SMOyuLs6E2Uk2q7dUOIlbRtipXSI6UtWRp3p7ZfNBRxqZ+TxcntyJCn9in2DZqIIgTWhACnB2dio7d50oCuuHX/O+PQHXhZKTVWOjL+8uS3f76cd0YvUNgV/i2h4KDdaGgsIYibnfaqEL5NznPaBklJ4vESknSaEfefY6IW5SSXeDfy/a8Bn0942jeSi5AKp+GGZqgePqq5RsqQkbEkSFUEO6mw+PkGjonSFCzL0nUOetTfzlVeHeBtC5zHnkFiNqzVvlprZf6PIxypCsY5oQ0oGTJOPuq6SGJrhnA67jlIG5NNhMJ5UCAtFCjNpADUl1hCiwM8jPGb+LRpX22Rn6ByeR0l+9vCYSNM9MVCMICgMABEJ4U+nlXA8aBKp/30BrhtChV+/6Gkj42K2fcD0Q==
  template:
    metadata:
      creationTimestamp: null
      name: onlyoffice-credentials
      namespace: homelab
