apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backup-sigilos-st-tls
  namespace: homelab
spec:
  secretName: backup-sigilos-st-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - backup.sigilos.st
