---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kopia-credentials
  namespace: homelab
spec:
  encryptedData:
    repo-password: AgA1v+6vWX8W1i1Wytws+dgiHHf188HGn2wAPqJqU1Bdfo/l8uA4pNqwJ5yhPHVSjJma5/sN1BOxnl70jWus+w46KsOPudDwCXI4k8IAqgXailamXDn9B6/8nZ0DXZpR+205m+wNgEYR26x7yZxXlt7PoXxicDV5qwAAWRhk6dI2mVssNijkcWZzkcpzc67YMIV9MSS8QYgKMF89JSeOu7T29vzx2b/hqreijdzr3FaEFrZ8nxBkVfjdLz2L1Mw4ZJwGZ5dJz92VWH5V9RZTV7gz5kv8vRge/XbI9jp3kdRIGtQbnsQpSiSSSAGe3adtWpmVIPF8fd9epe0Q4civ7SWy0xJbkqqBQ3EdLFBUsOnRv81t+Fr5O8LnsQWtN+TFkpILx26fdPJH2zHJdZkoNZHvGyYaFzIVkQ8l3kOHWDjimOCvpMivB1N8CwKSgChGjaiD3JB1oSLyMUwiRM5iHVHrA8l6UNicK1Kz0q6Rki/rufRCYgO8LWKUlPb8mvRY+J84QwHf7rK54/j8dSKZ9d0Dmr+0L20z1yoJsASfvEfJu7DPvcTgX02DhfOpnqG3SWWEH+AVBp0UDF0wQAvVxNSXG0XpmSWIWAyKUr4kKNig/E/Vs9U2WluVjRD1Sf6iLACW2srsQcWrVpNh20lY5XlJeSjnr3BqG87wHb3aHp+8zZLEROkaYT/CuLEbEojJZj7oHFSJ3Y5I6pKmT7BhyFPoEJPS+wew3qhYKTAoaD7z40+OxL+5bVa7
    server-password: AgCl3Dt75WSed9cfeyUEVEr07B3TOxd7DXGHMv200jHFrCbNNcUAsBpfxqeJCb878jsrps48t3KvEyB8aIRcyJTCH2sspJFdB5FbHg3i7KJJxbd92U3jRs/DA+pMG/bZWBpf7rUV1PxUWu109IeYbjmTSKkT/jNx5Qmsq8etU9ExMR/957RF514PzzEc4lSxUDvrCSG7H+TJR0Za8vw6wCD7DQ4JRKdlwW8ihSM6et82FU8SmW2FLl7za2CpnwqcdrdA4ZtABIvvepofKFlcptO3PoP5Q/yr7ElwVDFozudSaoNJL6ab/N7NAU7ZDK1v2oOq0iMFiKeWxdKgw3ZUrx9HiS/kL9rSp1y2VW06demJvzLfQhAQuxIOsL7jV7oWDxhSAUaK9PQlYfUcqUIXP7I5Cdn/GIdH5OLznBuU/5K8eP+GiBcLZ3iZKMUxXyf1x6qmUc3B3B+U9LV6ZtSTKI/t1LXAojqxi3rToUrJobsXEvgNvmdcMxXyU6x1rWNtf5Xb76kfa8TRNnbGG5D392MbuaCzykL8f1/UvfyzOgzC7K6lekF71GBro4fD4mXxNaJRpeHUdgLUcmpIcrgRuBqRpk9/Gd10dfJ+/c4OpK9V7ctuP1d+vrKnGy3kXEgdAeMdn4Cnkt7sH2sCeMRY1upj1b3LtyyLvt6GiM9Yxt8y+j7YK7o1JK3IZB006NK4TeDNmsloBUFDb4LUPCbAvv3mj9oV92OZVgF6XC3nZ5EnZjbKPQjkns6s
  template:
    metadata:
      creationTimestamp: null
      name: kopia-credentials
      namespace: homelab
