apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-sigilos-st-tls
  namespace: homelab
spec:
  secretName: sonarr-sigilos-st-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - sonarr.sigilos.st
