---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: homelab
spec:
  encryptedData:
    root-password: AgAZ3RsMjaXxpfBny4YNWjm0a5uB4zjRTYNZsoJLoE8Kcxu1iGHIrIGpguCnpdnK72k0qL4WW8/T7qqQ903+p0QA+z5yU0Ivp4IBKND5XjTVid0hkjxTovg3U7STpH0KBbkAN5o77yyHgGh6Jq0rom8dCW0ApDdt8SQJjtadIwwfobNVIxG265gk1vn9Ne0sRswIfj2Lxib2b31tL48e0wyIYrmGha1TgT59zJw7lyKusbZiuAApfkVJRp1eqRxi0I0jhW2oPU50WnbzsG+kMFRdyUjfo0o+u4skHhZmY8PqfxnVZK/xDTIg/esLZqTpC+JL7zSbg6rL/Y8WYLW8di1T5U37Op1iqSvra20ks4csbURowS4ghpElFOWhGyaP23U8VM3TpMcENDgj3MOhzWEtAVTUom0U3OoFfj6TumhTX8iCMdlZtNoqQZyc1HRHAR8OKeK8HUHzRzXuiSn1VrrAvG8BmYWR/XmaOBpTbU6ZRJG8lobwUROkGX1zcnDiBWJQBB0OaDlqijHPFBE7b1/eYTK6eBqN62J3ZZ5xhoh9e6549PQbS3M/aRCHHAqsH8vjRwY9hUDHDk7/dgsce3V9dtzWEkIxdw7lRHE3XPx25XOYh/flBNrIVQ/3UbDgsk5ce5g2hPRJZzYKmPuEq2vwMuG7YTDtaRLlnyQanyNpO+n5rO1VOmHlyMgmNhYBl/F8h8DiYqzeOzcN5HLSek346/vEEx3FJZMRTu742LH8Chwjd1zfBLaH
    root-user: AgB3xrf6W492P6pH41nNRcefVaKDAlYzdsUJe+ZSxBI9VNL1tlZm7SnCD1IUmmt68FYNjDUj0qJCT9IUCkHAydD6elJ9+X0Q8ngxmQw6gUq64vPhtj5CD28B9S2+OymtAApKF+I5eji9wJ9yntYiRbgfaAglSkO/NQeT81lQ70b8lPygVuZheEre1i/vslp9yU/4BHtj4oNiD5Rx0jWqooD3ln6E+97vefcYRGpdkQS5iH5WYGkI1jdI3Of+URQJ9TVnAQ13du1BUO6fFSDWqeJVy7QyJ2SXq6Kb/XdKzR9H2p1kQsW++5yC50vsIKOQiNw4q4IqrrJOsPS6LerlPrrgo2xbnSHS66PryXrVHM95SJFLDOnvlHwroA5kZMvPvIXuH+8rEbLhwfPRAjqoye/lMAEp/NWjRayqdlJvNtWbOrylmp5Bg2sKI1YjkLut8f9RfRIgAaBdV2xjO5/DgwxyPzzS99xgZ7PNhTh5rXA6QSKvS1eYUYbtRlkWAIQGUkdXv8593ptgN2vRYYffpkaxzvnc5VKBJUkSuk+s2PviBuSwZzADjF2EyTy0hIkXrgp4Et3pAUiUSffb/3EMTwsphZj9DGqnzl3aK5xaGrjqAXbNGXa/sCpiDBIIPYEoV3eEx/YuIBCLJUA9HWJY8TLjJovKdly0lTvuSwWIsE3vmjth4V+XyU0sJmhndq7kvIVfzNUVnQxjBD0l
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: homelab
