# Navidrome config - SSD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s/navidrome
---
# Music - HDD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /media/music
---
# qBittorrent config - SSD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s/qbittorrent
---
# Downloads - HDD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /media/downloads
---
# Prowlarr config - SSD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s/prowlarr
---
# Lidarr config - SSD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s/lidarr
---
# Flaresolverr config - SSD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flaresolverr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s/flaresolverr
---
# Soulseek config - SSD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slskd-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s/slskd
