apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: homelab
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - lidarr.sigilos.st
    secretName: lidarr-tls
  rules:
  - host: lidarr.sigilos.st
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lidarr
            port:
              number: 8686
